# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/airt-keras',
                'doc_host': 'https://airtai.github.io',
                'git_url': 'https://github.com/airtai/airt-keras',
                'lib_path': 'airt_keras'},
  'syms': {'airt_keras.core': {'airt_keras.core.foo': ('core.html#foo', 'airt_keras/core.py')}}}